import { expect, test } from "@playwright/test";

test("complete decision proof flow flips the recommendation and opens the report", async ({ page }, testInfo) => {
  const consoleErrors: string[] = [];
  page.on("console", (message) => {
    if (message.type() === "error") consoleErrors.push(message.text());
  });
  page.on("pageerror", (error) => consoleErrors.push(error.message));
  await page.goto("/");
  await expect(page.getByRole("heading", { name: "Turn AI recommendations into tests." })).toBeVisible();
  await expect(page.getByText("AI writes the recommendation. Decispec runs the tests.")).toBeVisible();
  await page.getByRole("link", { name: "Instant demonstration" }).click();
  await expect(page.getByText("Select Vendor A", { exact: true })).toBeVisible();
  await expect(page.locator("html")).toHaveAttribute("data-assert-hydrated", "true");
  await page.getByTestId("verify-decision").click();
  await expect(page.getByTestId("break-decision")).toBeVisible();
  await expect(page.getByLabel("Source documents").getByText("$18 per device per month", { exact: true })).toBeVisible();
  await page.getByTestId("break-decision").click();
  await expect(page.getByTestId("apply-correction")).toBeVisible();
  await expect(page.locator(".decision-banner").getByText("Decision broken", { exact: true })).toBeVisible();
  await expect(page.locator(".graph-focus-bar").getByText("Decision broken", { exact: true })).toBeVisible();
  await expect(page.getByRole("heading", { name: "Quote → Support cost → Vendor A total → Recommendation" })).toBeInViewport();
  const proofGraph = page.getByTestId("proof-graph");
  await expect(proofGraph).toHaveAttribute("data-graph-view", "focused");
  await expect(proofGraph.locator(".react-flow__node")).toHaveCount(4);
  await expect(proofGraph.getByText("Quote A · $18 / device / month")).toBeVisible();
  await expect(proofGraph.getByText("Student enrollment")).toHaveCount(0);
  await page.screenshot({ path: testInfo.outputPath("focused-failure-path.png"), fullPage: false });
  await page.getByTestId("toggle-graph-focus").click();
  await expect(proofGraph).toHaveAttribute("data-graph-view", "full");
  await expect(proofGraph.getByText("Student enrollment")).toBeVisible();
  await page.getByTestId("toggle-graph-focus").click();
  await expect(proofGraph).toHaveAttribute("data-graph-view", "focused");
  await expect(page.getByTestId("proof-diff")).toContainText("Vendor B");
  await page.getByTestId("proof-diff").scrollIntoViewIfNeeded();
  await page.screenshot({ path: testInfo.outputPath("correction-preview.png"), fullPage: false });
  await page.getByTestId("apply-correction").click();
  await expect(page.getByText("Select Vendor B", { exact: true })).toBeVisible();
  await expect(page.getByTestId("vendor-a-total")).toContainText("$268,677");
  await page.getByRole("link", { name: "View report" }).click();
  await expect(page.getByText("PROOF PASSED")).toBeVisible();
  await expect(page.locator(".report-stamp-passed")).toHaveCSS("color", "rgb(33, 106, 74)");
  await expect(page.getByText("Vendor B is $182,748 less expensive")).toBeVisible();
  await expect(page.getByText("Recommendation state · corrected")).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath("corrected-report.png"), fullPage: false });
  expect(consoleErrors).toEqual([]);
});
